name: Coveralls

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Coveralls GitHub Action     
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ github.token }}
        path-to-lcov:lcov.info